# Generated by Django 3.0.3 on 2020-04-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_auto_20200430_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
