# Generated by Django 2.2.3 on 2019-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
