# Generated by Django 2.2.3 on 2019-08-08 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_attendee_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 1, 55, 11, 341579, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
