# Generated by Django 2.2.3 on 2019-08-14 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_attendee_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 5, 26, 22, 697414, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
