# Generated by Django 2.2.3 on 2019-08-15 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_auto_20190814_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='history',
            new_name='time_log',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 3, 32, 26, 323054, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
