# Generated by Django 2.2.3 on 2019-08-15 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0006_auto_20190815_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='time_log',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 8, 8, 19, 708534, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
