# Generated by Django 2.2.3 on 2019-08-17 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0007_auto_20190815_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 5, 47, 46, 971527, tzinfo=utc), verbose_name='timestamp'),
        ),
        migrations.CreateModel(
            name='Time_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_log', models.TextField(null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.Attendee')),
            ],
        ),
    ]
