# Generated by Django 2.2.3 on 2019-08-17 06:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0008_auto_20190817_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 6, 17, 57, 539273, tzinfo=utc), verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='time_log',
            name='time_log',
            field=models.DateTimeField(null=True),
        ),
    ]
