# Generated by Django 2.2.3 on 2019-08-19 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0009_auto_20190817_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='value',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 10, 50, 36, 685678, tzinfo=utc), verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='time_log',
            name='time_log',
            field=models.DateTimeField(null=True, verbose_name='Time Logs'),
        ),
    ]
