# Generated by Django 2.2.3 on 2019-09-03 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0010_auto_20190819_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='first_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 7, 48, 19, 383914, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
