# Generated by Django 2.2.3 on 2019-09-03 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0016_auto_20190903_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 8, 2, 9, 117143, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
