# Generated by Django 2.2.3 on 2019-09-03 08:06

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0017_auto_20190903_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 8, 6, 17, 984560, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
