# Generated by Django 2.2.3 on 2019-09-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0020_auto_20190903_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_log', models.DateTimeField(null=True, verbose_name='Time Logs')),
                ('points_earned', models.IntegerField(default=0)),
                ('points_redeemed', models.IntegerField(default=0)),
                ('points_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='value',
        ),
        migrations.AddField(
            model_name='attendee',
            name='points_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendee',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendee',
            name='points_redeemed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.DeleteModel(
            name='Time_Log',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.Attendee'),
        ),
    ]
