# Generated by Django 2.2.3 on 2019-09-13 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0022_auto_20190913_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 5, 58, 18, 185763, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
