# Generated by Django 2.2.3 on 2019-09-14 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0023_auto_20190913_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='points_balance',
            new_name='total_points_balance',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='points_earned',
            new_name='total_points_earned',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='points_redeemed',
            new_name='total_points_redeemed',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='points_claim',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='points_redeem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 10, 7, 36, 566264, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
