# Generated by Django 2.2.3 on 2019-09-14 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0024_auto_20190914_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='points_claim',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='points_redeem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='total_points_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='total_points_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='total_points_redeemed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 11, 17, 36, 789730, tzinfo=utc), verbose_name='timestamp'),
        ),
    ]
