# Generated by Django 2.2.3 on 2019-11-05 10:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0025_auto_20190914_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 10, 9, 9, 598420, tzinfo=utc), verbose_name='timestamp'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='designation', to='attendees.Designation'),
        ),
    ]
