# Generated by Django 3.0.3 on 2020-02-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0027_auto_20200214_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='designation',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
